/**
 * Database types for the Rack Up section.
 *
 * Hand-maintained rather than generated. The Lovable project carried an
 * 813-line `types.ts` stamped "This file is automatically generated. Do not
 * edit it directly." which drifted out of date the moment anyone changed the
 * schema outside Lovable — and which described columns (`action_history`,
 * `current_player_index`, `rack_innings`) that the v2 schema no longer uses.
 *
 * This file covers only what the section actually reads and writes, so it
 * stays small enough to keep honest.
 */

import type { GameType } from "./rules/race";
import type { MatchEvent, MatchSetup, MatchState } from "./rules/match";
import type { Bracket, BracketType } from "./rules/bracket";

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/* -------------------------------------------------------------------------
 * Rows
 * ---------------------------------------------------------------------- */

export type ProfileRow = {
  id: string;
  name: string;
  avatar_url: string | null;
  skill_level: number | null;
  /** Per-game skill levels, e.g. { "8-ball": 5, "9-ball": 4 }. */
  skill_levels: Partial<Record<GameType, number>> | null;
  preferred_game_type: GameType | null;
  /**
   * APA member number; links to /roster/<id> on the main site.
   *
   * Read-only from the client — a database trigger refuses any update that
   * moves it. It is set only by an admin approving a roster claim.
   */
  apa_member_id: string | null;
  /** Can approve roster claims. Also client-read-only. */
  is_admin: boolean;
  /**
   * Someone entered by name so they can be scored without an account.
   *
   * A guest is an ordinary profile — that is what lets them hold a lifetime
   * record, a head-to-head and a seat at a table without any of those tables
   * growing a second kind of player.
   */
  is_guest: boolean;
  /** The account that entered this guest and may edit or remove them. */
  guest_owner: string | null;
  /** When the roster photo and skill levels were last pulled in. */
  apa_imported_at: string | null;
  created_at: string;
  updated_at: string;
};

export type RosterClaimRow = {
  id: string;
  user_id: string;
  apa_member_id: string;
  status: "pending" | "approved" | "rejected";
  note: string | null;
  requested_at: string;
  decided_at: string | null;
  decided_by: string | null;
};

/** A roster player as the claim picker and the importer see them. */
export type RosterPlayer = {
  id: string;
  name: string;
};

/** What /api/rack/roster/<id> returns — the importable bits of a roster page. */
export type RosterDetail = {
  id: string;
  name: string;
  skillLevel: number | null;
  /** Which game that skill level rates, so it lands on the right one. */
  format: string;
  profileImage: string | null;
};

export type RoomRow = {
  id: string;
  code: string;
  name: string;
  created_by: string;
  current_match_id: string | null;
  is_active: boolean | null;
  /** Set when the host closed the table. The matches it hosted are kept. */
  closed_at: string | null;
  created_at: string;
};

export type RoomPlayerRow = {
  id: string;
  room_id: string;
  user_id: string;
  joined_at: string;
};

export type MatchRow = {
  id: string;
  room_id: string;
  game_type: GameType;
  is_casual: boolean | null;
  status: "in_progress" | "complete" | "abandoned";
  /** Immutable setup; replaying the event log over it reproduces live_state. */
  setup: MatchSetup | null;
  /** Materialised snapshot — what spectators and the TV display read. */
  live_state: MatchState | null;
  version: number;
  player_ids: string[];
  winner_id: string | null;
  tournament_match_id: string | null;
  notes: string | null;
  started_at: string;
  ended_at: string | null;
  finalized_at: string | null;
  created_at: string;
};

export type MatchEventRow = {
  id: string;
  match_id: string;
  seq: number;
  event: MatchEvent;
  actor_id: string | null;
  created_at: string;
};

export type MatchPlayerRow = {
  id: string;
  match_id: string;
  user_id: string;
  score: number | null;
  race_to: number;
  innings: number | null;
  safeties: number | null;
  defensive_shots: number | null;
  timeouts_used: number | null;
  timeouts_remaining: number | null;
  break_and_runs: number | null;
  eight_on_breaks: number | null;
  rackless: number | null;
  broke_first: boolean | null;
};

export type PlayerStatsRow = {
  id: string;
  user_id: string;
  game_type: GameType;
  matches_played: number | null;
  wins: number | null;
  losses: number | null;
  break_and_runs: number | null;
  eight_on_breaks: number | null;
  total_innings: number | null;
  total_safeties: number | null;
  current_streak: number | null;
  longest_streak: number | null;
  skill_level: number | null;
};

export type HeadToHeadRow = {
  id: string;
  player1_id: string;
  player2_id: string;
  player1_wins: number | null;
  player2_wins: number | null;
  last_match_date: string | null;
};

export type TournamentRow = {
  id: string;
  room_id: string;
  name: string;
  game_type: GameType;
  bracket_type: BracketType;
  /** The generated bracket graph. Null until the tournament is seeded. */
  bracket: Bracket | null;
  /** Seed number -> user id, as a JSON object with numeric string keys. */
  seeds: Record<string, string> | null;
  status: "pending" | "in_progress" | "complete";
  winner_id: string | null;
  created_at: string;
  started_at: string | null;
  completed_at: string | null;
};

export type TournamentPlayerRow = {
  id: string;
  tournament_id: string;
  user_id: string;
  seed: number;
  placement: number | null;
  eliminated_at: string | null;
};

export type TournamentMatchRow = {
  id: string;
  tournament_id: string;
  /** Bracket slot this row records, e.g. "W1-3", "L2-1", "GF". */
  bracket_match_id: string | null;
  round: number;
  match_number: number;
  bracket: string;
  player1_id: string | null;
  player2_id: string | null;
  winner_id: string | null;
  /** The live match this bracket slot is being played as, if any. */
  match_id: string | null;
  status: "pending" | "in_progress" | "completed";
  started_at: string | null;
  completed_at: string | null;
};

export type PracticeSessionRow = {
  id: string;
  room_id: string;
  /** JSON-encoded array of { id, target } — see lib/rack/rules/drills.ts. */
  drill_type: string;
  created_at: string;
  ended_at: string | null;
};

export type PracticeSessionPlayerRow = {
  id: string;
  session_id: string;
  user_id: string;
  score: number | null;
  attempts: number | null;
  /** Per-drill scores, keyed by drill id. */
  drill_scores: Record<string, number> | null;
};

export type PracticeStatsRow = {
  id: string;
  user_id: string;
  drill_type: string;
  best_score: number | null;
  completions: number | null;
  total_attempts: number | null;
  created_at: string;
  updated_at: string;
};

/* -------------------------------------------------------------------------
 * RPC signatures
 * ---------------------------------------------------------------------- */

export type AppendEventResult = {
  version: number;
  live_state: MatchState | null;
  conflict: boolean;
};

/* -------------------------------------------------------------------------
 * Joined shapes used by the UI
 * ---------------------------------------------------------------------- */

export type RoomWithPlayers = RoomRow & {
  room_players: (RoomPlayerRow & { profiles: ProfileRow | null })[];
};

export type MatchWithProfiles = MatchRow & {
  match_players: (MatchPlayerRow & { profiles: ProfileRow | null })[];
};

/** Minimal profile shape the scoreboard and bracket need. */
export type PlayerBrief = Pick<
  ProfileRow,
  "id" | "name" | "avatar_url" | "apa_member_id"
> & {
  skill: number | null;
};

export function skillFor(
  profile: Pick<ProfileRow, "skill_level" | "skill_levels">,
  game: GameType,
): number | null {
  return profile.skill_levels?.[game] ?? profile.skill_level ?? null;
}

export function toBrief(profile: ProfileRow, game: GameType): PlayerBrief {
  return {
    id: profile.id,
    name: profile.name,
    avatar_url: profile.avatar_url,
    apa_member_id: profile.apa_member_id,
    skill: skillFor(profile, game),
  };
}
